### ISSUE TITLE
Attempted to set wl-extract to start the project, but compilation failed:

### ISSUE THREAD

**Issue by wutaijieing** [charlesnathansmith/whatlicense#1]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "public: bool __thiscall LEVEL_BASE::IPC_CLIENT::Init(enum LEVEL_BASE::IPC_TYPE)" (?Init@IPC_CLIENT@LEVEL_BASE@@QAE_NW4IPC_TYPE@2@@Z)，函数 "public: bool __thiscall LEVEL_PINSM::SM_CLIENT::Start(bool)" (?Start@SM_CLIENT@LEVEL_PINSM@@QAE_N_N@Z) 中引用了该符号	wl-extract	D:\8899\pin-3.28-98749-g6643ecee5-msvc-windows\source\tools\whatlicense\pin.lib(sm_client.cpp.obj)	1	
错误	LNK2019	无法解析的外部符号 "public: bool __thiscall LEVEL_BASE::IPC_CLIENT::RemoteProcedureCall(class std::basic_string<char,class std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,class std::char_traits<char>,class std::allocator<char> > *)" (?RemoteProcedureCall@IPC_CLIENT@LEVEL_BASE@@QAE_NABV?$basic_string@DV?$char_traits@D@std@@V?$allocator@D@2@@std@@PAV34@@Z)，函数 "public: class LEVEL_PINSM::SM_RESULT __thiscall LEVEL_PINSM::SM_CLIENT::GetLineInfoByAddress(unsigned int,unsigned int,unsigned int &,unsigned int &,class std::basic_string<char,class std::char_traits<char>,class std::allocator<char> > &)" (?GetLineInfoByAddress@SM_CLIENT@LEVEL_PINSM@@QAE?AVSM_RESULT@2@IIAAI0AAV?$basic_string@DV?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中引用了该符号	wl-extract	D:\8899\pin-3.28-98749-g6643ecee5-msvc-windows\source\tools\whatlicense\pin.lib(sm_client.cpp.obj)	1	
错误	LNK2019	无法解析的外部符号 "public: void __thiscall LEVEL_BASE::IPC_CLIENT::Close(void)" (?Close@IPC_CLIENT@LEVEL_BASE@@QAEXXZ)，函数 "public: __thiscall LEVEL_PINSM::SM_CLIENT::~SM_CLIENT(void)" (??1SM_CLIENT@LEVEL_PINSM@@QAE@XZ) 中引用了该符号	wl-extract	D:\8899\pin-3.28-98749-g6643ecee5-msvc-windows\source\tools\whatlicense\pin.lib(sm_client.cpp.obj)	1	
错误	LNK2019	无法解析的外部符号 "public: __thiscall LEVEL_BASE::IPC_CLIENT::~IPC_CLIENT(void)" (??1IPC_CLIENT@LEVEL_BASE@@QAE@XZ)，函数 "public: __thiscall LEVEL_PINSM::SM_CLIENT::~SM_CLIENT(void)" (??1SM_CLIENT@LEVEL_PINSM@@QAE@XZ) 中引用了该符号	wl-extract	D:\8899\pin-3.28-98749-g6643ecee5-msvc-windows\source\tools\whatlicense\pin.lib(sm_client.cpp.obj)	1	
错误	LNK1120	4 个无法解析的外部命令	wl-extract	D:\8899\pin-3.28-98749-g6643ecee5-msvc-windows\source\tools\whatlicense\bin\wl-extract.dll	1

**Comment by charlesnathansmith** [comment]
I was able to reproduce this issue.

The project was built with Pin 3.24 during testing and still builds against a clean install, but gives the same linking error you received when building against Pin 3.28

I tried gutting one of the demo tools packaged with version 3.28 and copying in the wl-extract files, and that built fine, so there's some sort of incompatibility between the project configurations.  I'll take a closer look in the morning and get back to you.  If they differences are irreconcilable, then I'll just migrate everything to 3.28

Thanks for letting me know

**Comment by charlesnathansmith** [comment]
I believe this issue has been fixed.  When building, be sure to select the Configuration matching the version of Pin you are building against: "Pin 3.26" for versions 3.26 and earlier, and "Pin 3.27+" for versions 3.27 and newer.

The only difference between configurations is that "Pin 3.27+" includes the "pinipc.lib" library to Additional Dependencies needed to build with those versions.

I'll leave this issue open for a few days in case any related problems spring up, then close it.

**Comment by wutaijieing** [comment]
Successfully compiled wl-extract.dll using pin3.27. Thank you
